### ISSUE TITLE
The FAB does not push up with snackbar alerts

### ISSUE THREAD

**Issue by duncanleo** [yavski/fab-speed-dial#12]
Hi,

The FAB view does not move up when a snackbar alert is shown. The FAB is placed as a child view in a CoordinatorLayout.

Thanks!

**Comment by yavski** [comment]
CoordinatorLayout has been supported since v1, it must have been broken in one of the minor releases. I'll look into it at the weekend.

**Comment by dstd** [comment]
@duncanleo check the sample app – a snackbar and FAB in example "Click Callback" are perfectly works together.

**Comment by yavski** [comment]
@duncanleo do you still have issues with CooridnatorLayout? Just checked it, nothing has been broken. Have a look at this example: [xml](https://github.com/yavski/fab-speed-dial/blob/master/samples/src/main/res/layout/activity_events_sample.xml) and [java](https://github.com/yavski/fab-speed-dial/blob/master/samples/src/main/java/io/github/yavski/fabspeeddial/samples/EventsSampleActivity.java). If it all works - close the issue. Otherwise provide me with some sample code.

**Comment by duncanleo** [comment]
@yavski sorry about the lack of a reply, but I'll check it out and let you know if I resolve it asap! Thanks for your help! :D

**Comment by duncanleo** [comment]
@yavski I've had a look at it.. I think it's a mistake on my part, I did this to create the snackbar:

``` java
Snackbar.make(MainActivity.this.findViewById(android.R.id.content), "Add group", Snackbar.LENGTH_LONG).show();
```

When in reality, the first parameter should be the `CoordinatorLayout` itself.

Sorry for troubling you!

**Comment by yavski** [comment]
No worries, glad it's resolved now then.
